# Generated by Django 3.2.18 on 2023-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20230704_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengroup',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
