# Generated by Django 3.2.18 on 2023-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_tokengroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokengroup',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
