# Generated by Django 3.2.18 on 2023-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_noncetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
