# Generated by Django 3.2.18 on 2023-09-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_alter_signature_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='was_used',
            field=models.BooleanField(default=False),
        ),
    ]
