# Generated by Django 3.2.18 on 2023-09-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_signature_was_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='tokenId',
            field=models.IntegerField(null=True),
        ),
    ]
