# Generated by Django 3.2.18 on 2023-06-26 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_invitationtoorganization_invitationtobecameuseradmin'),
        ('user_admin', '0003_auto_20230625_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organization.organization'),
            preserve_default=False,
        ),
    ]
