# Generated by Django 3.2.18 on 2023-06-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_course_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationtocourseasadmin',
            name='email',
        ),
        migrations.AddField(
            model_name='invitationtocourseasadmin',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_as_admin', to='user_admin.admin'),
            preserve_default=False,
        ),
    ]
