# Generated by Django 3.2.18 on 2023-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_alter_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitationToCourseAsAdmin',
        ),
    ]
