# Generated by Django 3.2.18 on 2024-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_delete_invitationtocourseasadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
