# Generated by Django 3.2.18 on 2024-01-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_course_is_admin_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_admin_approved',
        ),
    ]
