# Generated by Django 3.2.18 on 2023-06-23 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regular_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=30, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image')),
                ('identification_type', models.CharField(blank=True, max_length=20, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=20, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regular User',
                'verbose_name_plural': 'Regular Users',
            },
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='regular_user',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_courses', to='regular_user.userprofile'),
            preserve_default=False,
        ),
    ]
