# Generated by Django 3.2.18 on 2023-06-27 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regular_user', '0002_auto_20230623_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_courses', to='users.user'),
            preserve_default=False,
        ),
    ]
