# Generated by Django 3.2.18 on 2023-09-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_user', '0003_auto_20230627_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='identification_type',
        ),
    ]
